[package]
name = "flashcard-revision"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
chrono = "0.4.39"
rusqlite = {version = "0.32.1", features = ["bundled"]}
winit = "0.30.7"
wgpu = "23.0.1"
env_logger = "*"
log = "*"
pollster = "0.4.0"
